EComerceSite/urls.py
from . import views
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home  , name='home'),
    path('store/', include('store.urls')),
    path('cart/', include('carts.urls')),
    path('accounts/', include('accounts.urls')),
    path('orders/', include('orders.urls')),
    
       
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

carts/urls.py
from . import views
from .views import cart
from django.contrib import admin
from django.urls import path



urlpatterns = [
    path('',views.cart  , name='cart'),
    path('add_cart/<int:product_id>/',views.add_cart  , name='add_cart'),
    path('remove_cart/<int:product_id>/<int:cart_item_id>',views.remove_cart  , name='remove_cart'),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>',views.remove_cart_item  , name='remove_cart_item'),


    # path('<slug:category_slug>/<slug:product_slug>/',views.product_details  , name='product_details'),
    path('checkout/' ,views.checkout ,name='checkout'),
    
] 

store/urls.py
from . import views
from .views import store
from django.contrib import admin
from django.urls import path



urlpatterns = [
    path('',views.store  , name='store'),
    path('category/<slug:category_slug>/',views.store  , name='product_by_category'),
    path('category/<slug:category_slug>/<slug:product_slug>/',views.product_details  , name='product_details'),
    path('search/' , views.search , name='search'),
    path('submit_review/<int:product_id>/', views.submit_review  , name ='submit_review')

] 

store/models.py
from django.urls import reverse
from django.db import models
from category.models import Category
from accounts.models import Account
from django.db.models import Avg ,Count
# Create your models here.
class Product(models.Model):
    product_name    =models.CharField(max_length=200 , unique=True)
    slug            =models.SlugField(max_length=200 , unique=True)
    description     =models.CharField(max_length=500 , unique=True)
    price           =models.IntegerField()
    image           =models.ImageField(upload_to='photos/products')
    stock           =models.IntegerField()
    is_available    =models.BooleanField(default=True)
    category        =models.ForeignKey(Category, on_delete=models.CASCADE)
    created_date    =models.DateTimeField(auto_now_add=True)
    modified_date   =models.DateTimeField(auto_now=True)


    def get_url(self):
        return reverse('product_details' , args=[self.category.slug, self.slug]) 
         


    def __str__(self):
        return self.product_name
    
    # find avarage review to the produce
    # methanidi api avarage eka aragena eka float karala return karanawa eta passe apita puluwan average eka apita ona thana access karanna
    def averageReview(self):
        reviews = ReviewRating.objects.filter(product=self, status=True).aggregate(average=Avg('rating'))
        avg = 0
        if reviews['average'] is not None:
            avg = float(reviews['average'])
        return avg
    # review count eka ganna puluwan apita
    def countReview(self):
        reviews = ReviewRating.objects.filter(product=self, status=True).aggregate(count=Count('id'))
        count = 0
        if reviews['count'] is not None:
            count = int(reviews['count'])
        return count
    

class VariationManager(models.Manager):
    def colors(self):
        return super(VariationManager, self).filter(variation_category ='color' , is_active = True)
    
    def sizes(self):
        return super(VariationManager, self).filter(variation_category ='size' , is_active = True)


variation_category_choice = (
    ('color', 'color'),
    ('size' , 'size'),
    )

class Variation(models.Model):
    product = models.ForeignKey(Product , on_delete=models.CASCADE)
    variation_category = models.CharField(max_length=100,choices=variation_category_choice)
    variation_value = models.CharField(max_length=100)
    is_active = models.BooleanField(default=True)
    create_date = models.DateTimeField(auto_now=True)

    objects = VariationManager()


    def __str__(self):
        return self.variation_value       


class ReviewRating(models.Model):
    product = models.ForeignKey(Product , on_delete=models.CASCADE)
    user = models.ForeignKey(Account , on_delete=models.CASCADE)
    subject = models.CharField(max_length=100 , blank=True)
    review = models.TextField(max_length=500 , blank=True)
    rating = models.FloatField()
    ip = models.CharField(max_length=20 , blank=True)
    status = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.subject
        

class ABC(models.Model):
    name = models.CharField(max_length=100 , blank=True)


class Cde(ABC):
    age = models.CharField(max_length=100 ,blank=True)

store/forms.py
from django import forms
from .models import ReviewRating

class ReviewForm(forms.ModelForm):
    class Meta:
        model =ReviewRating
        fields = ['subject' , 'review' , 'rating']

store/views.py
from django.shortcuts import render ,get_object_or_404 ,redirect
from .models import Product ,ReviewRating
from .models import Category
from orders.models import OrderProduct
from .forms import ReviewForm
from django.contrib import messages ,auth
from carts.models import CartItem
from carts.views import _cart_id
from django.http import HttpResponse 
from django.core.paginator import EmptyPage,PageNotAnInteger,Paginator
from django.db.models import Q
# Create your views here.

def store(request,category_slug=None):
    categories = None
    products =None

    if category_slug != None:
        categories = get_object_or_404(Category ,slug = category_slug)
        products   =Product.objects.all().filter(category = categories , is_available=True)
        paginator = Paginator(products , 3)
        page = request.GET.get('page')
        page_product = paginator.get_page(page)
        product_count = products.count()
    else:
        products =Product.objects.all().filter(is_available =True).order_by('id')
        paginator = Paginator(products , 3)
        page = request.GET.get('page')
        page_product = paginator.get_page(page)
        product_count = products.count()
    
    context = {

        'products':page_product,
        'product_count':product_count
    }
    return render(request , 'store/store.html' , context)

# def product_by_category(request ,category_slug ):
#     categories =None
#     products =None
#     categories = get_object_or_404(Category,slug = category_slug )
#     products = Product.objects.all().filter(Category =categories ,is_available = True)
#     product_count = products.count()
#     context = {
#         'products':products,
#         'product_count':product_count
#     }
#     return render(request , 'store/store.html' , context)


def product_details(request ,category_slug,product_slug ):
    try:
        # category__slug mehema __ dekak dala apita puluwan vena app ekaka thiyenma model ekaka atribute ekak access karanna
        single_product = Product.objects.get(category__slug = category_slug , slug = product_slug)
        in_cart = CartItem.objects.filter(cart__cart_id = _cart_id(request) , product = single_product).exists()
    except Exception as e:
        raise e
    
# methanin user order ekak gaththgothada nadda kiyala balanawa true , false da kiyala  
# methana error ekak enawa
# Field 'id' expected a number but got <SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x00000296EE37A8D0>>.
# ekanisa methanata if ekak danawa
    if request.user.is_authenticated:
        try:
            orderproduct =OrderProduct.objects.filter(user = request.user , product_id = single_product.id).exists()
        except OrderProduct.DoesNotExist:
            orderproduct =None
    else:
        orderproduct =None

# Get the review
    reviews = ReviewRating.objects.filter(product_id = single_product.id , status = True)

    context = {
        'single_product':single_product,
        'in_cart' : in_cart,
        'orderproduct':orderproduct,
        'reviews' : reviews,
    }

    return render(request , 'store/product_details.html' ,context)




def search(request):
    if 'keyword' in request.GET:
        keyword = request.GET['keyword']
        if keyword:
            Products = Product.objects.order_by('-created_date').filter(Q(description__icontains = keyword) | Q(product_name__icontains = keyword))
            product_count = Products.count()
        context = {
            'products':Products,
             'product_count':product_count   
        }
    return render(request , 'store/store.html',context )



def submit_review(request , product_id):
    url =request.META.get('HTTP_REFERER')
    if request.method == 'POST':
        try:
            # methana __id kiyala dala thiyenne user ge id eka ganna acount eken mkd user acount ekath ekka foreign key nisa
            # product__id ekath foreign key nisa ReviewRating wala
            reviews = ReviewRating.objects.get(user__id = request.user.id , product__id = product_id)
            form = ReviewForm(request.POST , instance = reviews)
            form.save()
            messages.success(request , 'Thank You! You review has been updated.')
            return redirect(url)
        except ReviewRating.DoesNotExist:
            form = ReviewForm(request.POST)
            if form.is_valid():
                data = ReviewRating()
                data.subject = form.cleaned_data['subject']
                data.rating = form.cleaned_data['rating']
                data.review = form.cleaned_data['review']
                data.ip = request.META.get('REMOTE_ADDR')
                data.product_id = product_id
                data.user_id = request.user.id
                data.save()
                messages.success(request , 'Thank You! You review has been submited.')
                return redirect(url)

templates/store/product_details.html
{% extends 'base.html' %}
{% load static %}
{%block content%}


<section class="section-content padding-y bg">
    <div class="container">
    
    <!-- ============================ COMPONENT 1 ================================= -->
    <div class="card">
        <div class="row no-gutters">
            <aside class="col-md-6">
              <article class="gallery-wrap"> 
                <a href="#"><img src={{single_product.image.url}}></a>
        {% comment %} </div> <!-- img-big-wrap.// --> {% endcomment %}
              </article> <!-- gallery-wrap .end// -->
            </aside>
            <main class="col-md-6 border-left">
             <div class="img-big-wrap">

              <form action="{% url 'add_cart' single_product.id %}" method="POST">
                    {% csrf_token %} 
                    <article class="content-body">
                      
                      <h2 class="title">{{ single_product.product_name }}</h2>
                      <div class="rating-star">
                        <span>
                          <i class="fa fa-star{% if single_product.averageReview < 0.5 %}-o{% elif single_product.averageReview >= 0.5 and single_product.averageReview < 1 %}-half-o {% endif %}" aria-hidden="true"></i>
                          <i class="fa fa-star{% if single_product.averageReview < 1.5 %}-o{% elif single_product.averageReview >= 1.5 and single_product.averageReview < 2 %}-half-o {% endif %}" aria-hidden="true"></i>
                          <i class="fa fa-star{% if single_product.averageReview < 2.5 %}-o{% elif single_product.averageReview >= 2.5 and single_product.averageReview < 3 %}-half-o {% endif %}" aria-hidden="true"></i>
                          <i class="fa fa-star{% if single_product.averageReview < 3.5 %}-o{% elif single_product.averageReview >= 3.5 and single_product.averageReview < 4 %}-half-o {% endif %}" aria-hidden="true"></i>
                          <i class="fa fa-star{% if single_product.averageReview < 4.5 %}-o{% elif single_product.averageReview >= 4.5 and single_product.averageReview < 5 %}-half-o {% endif %}" aria-hidden="true"></i>
                             <span>{{single_product.countReview }} reviews</span>
                          </span>
                      </div>
                      <div class="mb-3"> 
                        <var class="price h4">${{ single_product.price}}</var> 
                      </div> 
                      
                      <p>{{ single_product.description}}</p>
                      
                      <hr>
                      <div class="row">
                        <div class="item-option-select">
                          <h6>Choose Color</h6>
                          <select name = "color" class="form-control" required>
                            <option value="" disabled Selected>Select </option>
                            {% for i in  single_product.variation_set.colors %}
                                  <option value = "{{i.variation_value | lower}}">{{ i.variation_value |capfirst}}</option>
                            {% endfor %}
                          </select>   
                        </div>
                      </div> 
                      <div class="row">
                        <div class="item-option-select">
                          <h6>Select Size</h6>
                          <select name = "size" class="form-control">
                            <option value="" disabled Selected>Select</option>
                            {% for i in  single_product.variation_set.sizes %}
                                  <option value = "{{i.variation_value | lower}}">{{ i.variation_value | capfirst }}</option>
                            {% endfor %}
                          </select>   
                        </div>
                      </div>
                  
                      <hr>
                      {% if single_product.stock <= 0 %}
                        <h4 class="text-danger"> Out Of Stock</h4>
                      {% else %}
                          {% comment %} {% if in_cart%}
                              <a  href="#" class="btn  btn-success"> <span class="text">Added to cart</span> <i class="fas fa-check"></i>  </a>
                              <a  href="{% url 'cart'  %}" class="btn  btn-outline-primary"> <span class="text">View cart</span> <i class="fas fa-eye"></i>  </a>
                          {%else%} {% endcomment %}
                              <button type="submit" class="btn  btn-primary"> <span class="text">Add to Cart</span> <i class="fas fa-shopping-cart"></i> </button>
                          {% comment %} {% endif %}     {% endcomment %}
                      {% endif %}
                    </article> <!-- product-info-aside .// -->
            </form>       
        
            </main> <!-- col.// -->
                </div> <!-- row.// -->
            </div> <!-- card.// -->
            <!-- ============================ COMPONENT 1 END .// ================================= -->
            
            <br>
            
            <div class="row">
                        <div class="col-md-9">
            
             

                <form action=" {% url 'submit_review' single_product.id %} " method="POST">
                  {%csrf_token%}
                  <h5>Write Your Review</h5>
                  <label>How do you rate this product?</label>
                  <br>
                  <div>

                    <div class="rate">
                      <input type="radio" name="rating" id="rating10" value="5" required /><label for="rating10" title="5"></label>
                      <input type="radio" name="rating" id="rating9" value="4.5" required /><label for="rating9" title="4.5" class="half"></label>
                      <input type="radio" name="rating" id="rating8" value="4" required /><label for="rating8" title="4"></label>
                      <input type="radio" name="rating" id="rating7" value="3.5" required /><label for="rating7" title="3.5" class="half"></label>
                      <input type="radio" name="rating" id="rating6" value="3" required /><label for="rating6" title="3"></label>
                      <input type="radio" name="rating" id="rating5" value="2.5" required /><label for="rating5" title="2.5" class="half"></label>
                      <input type="radio" name="rating" id="rating4" value="2" required /><label for="rating4" title="2"></label>
                      <input type="radio" name="rating" id="rating3" value="1.5" required /><label for="rating3" title="1.5" class="half"></label>
                      <input type="radio" name="rating" id="rating2" value="1" required /><label for="rating2" title="1"></label>
                      <input type="radio" name="rating" id="rating1" value="0.5" required /><label for="rating1" title="0.5" class="half"></label>
                    </div>


                    Review title:
                      <input type="text" class="form-control" name="subject">
                      <br>
                    
                    Review:
                    <textarea name="review" rows="4" class="form-control"></textarea>
                    <br>
                   {% if user.is_authenticated %} 
                      {% if orderproduct %}
                          <input type="submit" value="Submit Review" class="btn btn-primary">
                      {% else%}
                          <p> You must purchase this product to post a review </p>
                      {%endif%}
                   {% else %}
                    <p> You must be logged  in to post a review <span><a href= "{% url 'login' %}"> Login now </a> </p>
                    {% endif%}
                    <br>

                  </div>
                    {% include 'root/Alert.html' %}
                </form>




                <br>
                <header class="section-heading">
                  <h3>Customer Reviews </h3>
                  <div class="rating-star">
                    <span>
                      <i class="fa fa-star{% if single_product.averageReview < 0.5 %}-o{% elif single_product.averageReview >= 0.5 and single_product.averageReview < 1 %}-half-o {% endif %}" aria-hidden="true"></i>
                      <i class="fa fa-star{% if single_product.averageReview < 1.5 %}-o{% elif single_product.averageReview >= 1.5 and single_product.averageReview < 2 %}-half-o {% endif %}" aria-hidden="true"></i>
                      <i class="fa fa-star{% if single_product.averageReview < 2.5 %}-o{% elif single_product.averageReview >= 2.5 and single_product.averageReview < 3 %}-half-o {% endif %}" aria-hidden="true"></i>
                      <i class="fa fa-star{% if single_product.averageReview < 3.5 %}-o{% elif single_product.averageReview >= 3.5 and single_product.averageReview < 4 %}-half-o {% endif %}" aria-hidden="true"></i>
                      <i class="fa fa-star{% if single_product.averageReview < 4.5 %}-o{% elif single_product.averageReview >= 4.5 and single_product.averageReview < 5 %}-half-o {% endif %}" aria-hidden="true"></i>
                  <span>{{single_product.countReview}} reviews</span>
                      </span>
                  </div>                
              </header>
        {% for review in reviews %}
                <article class="box mb-3">
                    <div class="icontext w-100">
                        <img src={%static "./images/avatars/avatar1.jpg" %} class="img-xs icon rounded-circle">
                        <div class="text">
                            <span class="date text-muted float-md-right">{{review.updated_at}} </span>  
                            <h6 class="mb-1">{{ review.user.full_name }} </h6>
                            <div class="rating-star">
                              <span>
                                <i class="fa fa-star{% if review.rating == 0.5 %}-half-o{% elif review.rating < 1 %}-o {% endif %}" aria-hidden="true"></i>
                                <i class="fa fa-star{% if review.rating == 1.5 %}-half-o{% elif review.rating < 2 %}-o {% endif %}" aria-hidden="true"></i>
                                <i class="fa fa-star{% if review.rating == 2.5 %}-half-o{% elif review.rating < 3 %}-o {% endif %}" aria-hidden="true"></i>
                                <i class="fa fa-star{% if review.rating == 3.5 %}-half-o{% elif review.rating < 4 %}-o {% endif %}" aria-hidden="true"></i>
                                <i class="fa fa-star{% if review.rating == 4.5 %}-half-o{% elif review.rating < 5 %}-o {% endif %}" aria-hidden="true"></i>
                              </span>
                            </div>
                        </div>
                    </div> <!-- icontext.// -->
                    <div class="mt-3">
                      <h6> {{ review.subject }}</h6>
                        <p>
                           {{ review.review}}
                        </p>	
                    </div>
                </article>
        {% endfor%}


        </div> <!-- col.// -->
    </div> <!-- row.// -->
    
    
    </div> <!-- container .//  -->
    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->
    
    </body>
    </html>
    {%endblock%}

templates/store/store.html
{%extends 'base.html'%}

{% block content%}
</head>
<body>


<!-- ========================= SECTION PAGETOP ========================= -->
<section class="section-pagetop bg">
<div class="container">
	{% if 'search' in request.path %}
	<h2 class="title-page">Search Result</h2>
	{% else%}
	<h2 class="title-page">Our Store</h2>
	{%endif%}

</div> <!-- container //  -->
</section>
<!-- ========================= SECTION INTRO END// ========================= -->

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-content padding-y">
<div class="container">

<div class="row">
	<aside class="col-md-3">
		
<div class="card">
	<article class="filter-group">
		<header class="card-header">
			<a href="#" data-toggle="collapse" data-target="#collapse_1" aria-expanded="true" class="">
				<i class="icon-control fa fa-chevron-down"></i>
				<h6 class="title">Categories</h6>
			</a>
		</header>
		<div class="filter-content collapse show" id="collapse_1" style="">
			<div class="card-body">
				
				<ul class="list-menu">
					<li><a href="{% url 'store' %}">All Product</a></li>
				{% for Categories in links%}
					<li><a href="{{Categories.get_url}}">{{ Categories.category_name}}</a></li>
				{%endfor%}
				</ul>

			</div> <!-- card-body.// -->
		</div>
	</article> <!-- filter-group  .// -->
	<article class="filter-group">
		<header class="card-header">
			<a href="#" data-toggle="collapse" data-target="#collapse_4" aria-expanded="true" class="">
				<i class="icon-control fa fa-chevron-down"></i>
				<h6 class="title">Sizes </h6>
			</a>
		</header>
		<div class="filter-content collapse show" id="collapse_4" style="">
			<div class="card-body">
			  <label class="checkbox-btn">
			    <input type="checkbox">
			    <span class="btn btn-light"> XS </span>
			  </label>

			  <label class="checkbox-btn">
			    <input type="checkbox">
			    <span class="btn btn-light"> SM </span>
			  </label>

			  <label class="checkbox-btn">
			    <input type="checkbox">
			    <span class="btn btn-light"> LG </span>
			  </label>

			  <label class="checkbox-btn">
			    <input type="checkbox">
			    <span class="btn btn-light"> XXL </span>
			  </label>
		</div><!-- card-body.// -->
		</div>
	</article> <!-- filter-group .// -->
	
	<article class="filter-group">
		<header class="card-header">
			<a href="#" data-toggle="collapse" data-target="#collapse_3" aria-expanded="true" class="">
				<i class="icon-control fa fa-chevron-down"></i>
				<h6 class="title">Price range </h6>
			</a>
		</header>
		<div class="filter-content collapse show" id="collapse_3" style="">
			<div class="card-body">
				
				<div class="form-row">
				<div class="form-group col-md-6">
				  <label>Min</label>
				  <!-- <input class="form-control" placeholder="$0" type="number"> -->
				  	<select class="mr-2 form-control">
						<option value="0">$0</option>
						<option value="50">$50</option>
						<option value="100">$100</option>
						<option value="150">$150</option>
						<option value="200">$200</option>
						<option value="500">$500</option>
						<option value="1000">$1000</option>
					</select>
				</div>
				<div class="form-group text-right col-md-6">
				  <label>Max</label>
				  	<select class="mr-2 form-control">
						<option value="50">$50</option>
						<option value="100">$100</option>
						<option value="150">$150</option>
						<option value="200">$200</option>
						<option value="500">$500</option>
						<option value="1000">$1000</option>
						<option value="2000">$2000+</option>
					</select>
				</div>
				</div> <!-- form-row.// -->
				<button class="btn btn-block btn-primary">Apply</button>
			</div><!-- card-body.// -->
		</div>
	</article> <!-- filter-group .// -->
	
</div> <!-- card.// -->

	</aside> <!-- col.// -->
	<main class="col-md-9">

<header class="border-bottom mb-4 pb-3">
		<div class="form-inline">
			<span class="mr-md-auto"><b>{{ product_count }} </b> Items found </span>
			
		</div>
</header><!-- sect-heading -->

<div class="row">
	{% if products%}
	{% for products in products%}
	<div class="col-md-4">
		<figure class="card card-product-grid">
			<div class="img-wrap"> 
				
				<a href={{products.get_url}}><img src="{{ products.image.url }}"></a>
				
			</div> <!-- img-wrap.// -->
			<figcaption class="info-wrap">
				<div class="fix-height">
					<a href="{{ products.get_url }}" class="title">{{products.product_name}}</a>
					<div class="price-wrap mt-2">
						<span class="price">$ {{products.price}}</span>
						<del class="price-old">$1980</del>
					</div> <!-- price-wrap.// -->
				</div>
				<a href={{ products.get_url }} class="btn btn-block btn-primary">View Details </a>
			</figcaption>
		</figure>
	</div> <!-- col.// -->
	{% endfor %}
	{%else%}
	<div>
		<h2>No result Found . Please Try again Later </h2>
	</div>
	{%endif%}
</div> <!-- row end.// -->


<nav class="mt-4" aria-label="Page navigation sample">
	{% if products.has_other_pages %}
		<ul class="pagination">

			{% if products.has_previous %}
			<li class="page-item "><a class="page-link" href="?page={{products.previous_page_number }}">Previous</a></li>
			{% else %}
			<li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
			{%endif%}
			
			{%for i in products.paginator.page_range%}	
				{% if products.number == i %}
					<li class="page-item active"><a class="page-link" href="#">{{i}}</a></li>
				{% else %}
					<li class="page-item "><a class="page-link" href="?page={{i}}">{{i}}</a></li>
				{% endif %}
			{% endfor %}	
			
			{% if products.has_next%}
				<li class="page-item"><a class="page-link" href="?page={{products.next_page_number }}">Next</a></li>
			{% else %}
				<li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
			{% endif %}
		</ul>
	{% endif %}	
</nav>

	</main> <!-- col.// -->

</div>

</div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->
</body>
</html>
{% endblock %}